In [1]:
import numpy as np
a = np.array([2,-1,8,6])
a

array([ 2, -1,  8,  6])

In [2]:
a.min()

-1

In [3]:
a[3]

6

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [6]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
import pandas as pd
s = pd.Series(range(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [9]:
data = pd.DataFrame(s)
data

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [11]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [14]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
arr = np.arange(1,10)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[3:6]

array([4, 5, 6])

In [17]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [18]:
arr[::-2]

array([9, 7, 5, 3, 1])

In [19]:
arr[::-3]

array([9, 6, 3])

In [20]:
arr2 = arr
arr2



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2[1:3] = [17,19]
arr2

array([ 1, 17, 19,  4,  5,  6,  7,  8,  9])

In [22]:
arr

array([ 1, 17, 19,  4,  5,  6,  7,  8,  9])

In [23]:
arr2[arr2 >= 5]

array([17, 19,  5,  6,  7,  8,  9])

In [24]:
arr2[(arr2 >= 5) & (arr2 <= 10)]

array([5, 6, 7, 8, 9])

In [25]:
arr.resize(3,3)

In [26]:
arr

array([[ 1, 17, 19],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
arr.ravel()

array([ 1, 17, 19,  4,  5,  6,  7,  8,  9])

In [31]:
arr.reshape(3,-1)

array([[ 1, 17, 19],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
np.sort(arr.ravel())

array([ 1,  4,  5,  6,  7,  8,  9, 17, 19])

In [36]:
arr

array([[ 1, 17, 19],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [38]:
sorted(arr.ravel(),reverse=True)

[19, 17, 9, 8, 7, 6, 5, 4, 1]

In [40]:
# axis = 0 表示按行进行操作
# axis = 1 表示按列进行操作
import datetime
datetime.datetime.now()

datetime.datetime(2020, 6, 7, 21, 14, 57, 128632)

In [43]:
lis = arr.ravel()
lis

array([ 1, 17, 19,  4,  5,  6,  7,  8,  9])

In [42]:
lis.cumsum()

array([ 1, 18, 37, 41, 46, 52, 59, 67, 76], dtype=int32)

In [45]:
np.percentile(lis,10)

3.4000000000000004